planner_frequency: 1.0
planner_patience : 2.0

controller_frequency: 10.0
controller_patience :  3.0

oscillation_timeout : 10.0
oscillation_distance:  0.2

recovery_behavior_enabled: true
shutdown_costmaps        : false
